[versions]
collection = "1.5.0"
kotlin = "2.3.0"
android-minSdk = "24"
android-compileSdk = "36"
kotlinter = "5.3.0"
kermit = "2.0.8"
dokka = "2.1.0"
compose = "1.9.3"
androidsvg = "1.4"
kobweb = "0.23.3"
lifecycleRuntime = "2.10.0"
agp = "8.13.2"
vanniktech = "0.35.0"

[libraries]
collection = { module = "androidx.collection:collection", version.ref = "collection" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
androidsvg = { group = "com.caverock", name = "androidsvg", version.ref = "androidsvg" }
kobweb-compose = { module = "com.varabyte.kobweb:kobweb-compose", version.ref = "kobweb" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycleRuntime" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleRuntime" }

[plugins]
androidLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-kotlin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
